# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml


trigger:
- master


pool:
  vmImage: 'windows-latest'


variables:
  solution: '**/*.sln'
  buildPlatform: 'x86|x64'
  buildConfiguration: 'Release'
  triplet: 'x64-windows'


steps:
- script: |
    git clone https://github.com/Microsoft/vcpkg
    cd vcpkg
    call .\bootstrap-vcpkg.bat
    call .\vcpkg integrate install
    call .\vcpkg install tiff openjpeg fastcgi libpng libwebp libavif[aom] --triplet x64-windows
  displayName: Install dependencies using vcpkg

- task: MSBuild@1
  inputs:
    solution: 'windows/Visual Studio 2022/iipsrv-MSVC2022.sln'
    msbuildArchitecture: 'x64'
    platform: 'x64'
    configuration: 'Release'
